### ISSUE TITLE
Implement networking module across forks

### ISSUE THREAD

**Issue by brech1** [ralexstokes/ethereum-consensus#185]
## Description

The current [networking.rs](https://github.com/ralexstokes/ethereum-consensus/blob/main/src/networking.rs) module only implements the [phase0](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md) p2p interface specs.

Since the general approach is to duplicate the definitions across spec versions, a proposed solution is to make a new networking module for each fork with the correct types.

**Comment by ralexstokes** [comment]
fixed in #186
