### ISSUE TITLE
Implement the altair spec

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/ethereum-consensus#21]
The altair spec, e.g. here: https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/beacon-chain.md

We will want to leverage as much of the phase 0 spec code as possible and this may require some care to make sure we can leverage multiple types etc. like an `apply_block` function that can take either spec's state, block types, or various functions that take a `Context` for each version of the spec

**Comment by buchhlz2** [comment]
An overview of what's to be included:
- custom types
    - [ ]  ParticipationFlags
- constants
    - [ ]  TIMELY_SOURCE_FLAG_INDEX
    - [ ]  TIMELY_TARGET_FLAG_INDEX
    - [ ]  TIMELY_HEAD_FLAG_INDEX
    - [ ]  TIMELY_SOURCE_WEIGHT
    - [ ]  TIMELY_TARGET_WEIGHT
    - [ ]  TIMELY_HEAD_WEIGHT
    - [ ]  SYNC_REWARD_WEIGHT
    - [ ]  PROPOSER_WEIGHT
    - [ ]  WEIGHT_DENOMINATOR
    - [ ]  DOMAIN_SYNC_COMMITTEE
    - [ ]  DOMAIN_SYNC_COMMITTEE_SELECTION_PROOF
    - [ ]  DOMAIN_CONTRIBUTION_AND_PROOF
    - [ ]  PARTICIPATION_FLAG_WEIGHTS
- preset
    - [ ]  INACTIVITY_PENALTY_QUOTIENT_ALTAIR
    - [ ]  MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR
    - [ ]  PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR
    - [ ]  SYNC_COMMITTEE_SIZE
    - [ ]  EPOCHS_PER_SYNC_COMMITTEE_PERIOD
- config
    - [ ]  INACTIVITY_SCORE_BIAS
    - [ ]  INACTIVITY_SCORE_RECOVERY_RATE
- containers
    - [ ]  `BeaconBlockBody` → add `sync_aggregate`
    - [ ]  `BeaconState`
        - [ ]  add `inactivity_scores`, `current_sync_committee`, & `next_sync_committee`
        - [ ]  modify `previous_epoch_participation` & `current_epoch_participation`
    - [ ]  `SyncAggregate`
    - [ ]  `SyncCommittee`
- helper fns
    - misc
        - [ ]  `add_flag`
        - [ ]  `has_flag`
    - Beacon state accessors
        - add
            - [ ]  `get_next_sync_committee_indices`
            - [ ]  `get_next_sync_committee`
            - [ ]  `get_base_reward_per_increment`
            - [ ]  `get_unslashed_participating_indices`
            - [ ]  `get_attestation_participation_flag_indices`
            - [ ]  `get_flag_index_deltas`
        - modify
            - [ ]  `get_base_reward`
            - [ ]  `get_inactivity_penalty_deltas`
    - Beacon state mutators
        - modify
            - [ ]  `slash_validator`
    - block processing
        - add
            - [ ]  `process_sync_aggregate` (added to `process_block`)
        - modify
            - [ ]  `process_operations`
            - [ ]  `process_attestation`
            - [ ]  `process_deposit`
    - epoch processing
        - add
            - [ ]  `process_inactivity_updates`
            - [ ]  `process_participation_flag_updates`
            - [ ]  `process_sync_committee_updates`
        - modify
            - [ ]  `process_justification_and_finalization`
            - [ ]  `process_rewards_and_penalties`
            - [ ]  `process_slashings`
    - initialize state (for testnets & test vectors)
        - modify
            - [ ]  `initialize_beacon_state_from_eth1`

**Comment by buchhlz2** [comment]
I'll hold off on starting anything for now -- I'll need to make sure I'm aligned on how to structure these within the context of the overall project. For example, Lighthouse separates "phase 0" and "altair" into their own modules but puts them under `epoch_processing`, `presets`, etc....aka lower in the hierarchy.

At least in its current structure, it looks like this project aims to keep `phase0` and `altair` entirely separated at the top level, similar to how Lodestar organizes their implementation. Thus:
1. The `altair` module should follow a similar layout as `phase0` (configs, presets, state transition, etc.), import `phase0` where needed, and then modify/add new features? 
2. `crypto`, `domains`, and `primitives` are common types (as in, these are at the same level as `altair` and `phase0` within `src`). If something needs to be added/modified here for Altair (e.g., adding `ParticipationFlags` to `primitives.rs`), should the change take place within the `altair` module or in the existing file under `src`?

**Comment by ralexstokes** [comment]
i wanted to think about how to best implement both specs without having to duplicate all of the shared functionality.

lighthouse basically wraps each variant in an enum which is what is passed to each function.

each function can then match on the state to get the relevant information/data it needs....

we can for now go ahead w/ defining the new stuff, like an `altair.BeaconState` along w/ the new functionality that uses it `fn process_sync_committee_updates(state: &mut altair.BeaconState, context: &Context)` and i'll think about how best to unify everything

**Comment by ralexstokes** [comment]
> hing needs to be added/modified here for Altair (e.g., adding ParticipationFlags to primitives.rs), should the change take place within the altair module or in the existing file under src?

i'm fine putting the common stuff in the common places without separating by phase

**Comment by ralexstokes** [comment]
note: will want custom serialization for the flags which are sent over the API as individual `u8` encoded as decimal strings
