### ISSUE TITLE
`capella`: impl `process_withdrawals`

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/ethereum-consensus#250]
[`process_withdrawals`](https://github.com/ralexstokes/ethereum-consensus/blob/61836a64464f311a40fd3038edf774f5c239e3ea/ethereum-consensus/src/capella/block_processing.rs#L264) following: https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#new-process_withdrawals

**Comment by chirag-bgh** [comment]
I will take this.

**Comment by Perelyn-sama** [comment]
github mev is real, I was trying to frontrun @chirag-bgh then boom @PatStiles frontruns us both
