### ISSUE TITLE
update usage of `U256` from latest `ssz-rs` update

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/ethereum-consensus#298]
this type was refactored to use `alloy-primitives' impl in https://github.com/ralexstokes/ssz-rs/pull/113

updating this repo should be pretty straightforward with possibly a few API changes (see the ssz-rs PR for some things that changed)

another breaking change was inheriting the included `serde` impl which encodes a U256 as a hex-string. this deviates from the `beacon-apis` spec which encodes `U256` as a decimal string. we should be able to easily fix this with an `#[serde(with = "crate::serde::as_str")]` attribute on any type in this repo that uses `U256` (e.g. see how we handle `Slot`)

**Comment by Perelyn-sama** [comment]
I'll try it

**Comment by 0xJepsen** [comment]
Down to take this over the weekend if you don't get to it @Perelyn-sama
