### ISSUE TITLE
can't query validators by pubkeys due to readable bytes array formatting 

### ISSUE THREAD

**Issue by Doozers** [ralexstokes/ethereum-consensus#309]
Hi, wanted to use the [get_validators()](https://github.com/ralexstokes/ethereum-consensus/blob/main/beacon-api-client/src/api_client.rs#L156) method to query validators by pubeys, but the query failed cause the id parameter looks like that: "0xABCD…ABCD,0xABCD…ABCD,0xABCD…ABCD"

it is due to the following logic: 
`let validator_ids = validator_ids.iter().join(",");`

Display for bytes vector: https://github.com/ralexstokes/ethereum-consensus/blob/main/ethereum-consensus/src/ssz/byte_vector.rs#L32

I did a temp fix on a fork [here](https://github.com/Doozers/ethereum-consensus/commit/7130763ddd56174af5e9e911c22a0d620e2bfade), not sure that's what you plan to do but if it's the case I can do a PR. :)

**Comment by ralexstokes** [comment]
ah sorry about this! no tests for the api client :(

I'll go fix now, I'd rather keep the debug/display on `ByteVector`; instead ill go fix that API code

**Comment by ralexstokes** [comment]
@Doozers this should be fixed now on `main`, please let me know if there is still an issue, thanks!
