### ISSUE TITLE
Verify `verify_blob_sidecar_inclusion_proof` with test data

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/ethereum-consensus#363]
add a unit test with live data from e.g. sepolia and verify this function

**Comment by EchoAlice** [comment]
i've got u

**Comment by ralexstokes** [comment]
@EchoAlice this is the type of test I have in mind

https://github.com/ralexstokes/ethereum-consensus/blob/0e8809c1eda3f54a78991d7a5987ff42c9195d42/ethereum-consensus/src/serde.rs#L64

just loading some hardcoded json and then running some functions on it

**Comment by ralexstokes** [comment]
if we can update the `ssz-rs` dep, we should also test that the merkle proving code there works to generate valid KZG inclusion proofs
