### ISSUE TITLE
PayloadAttributes struct fields are not public

### ISSUE THREAD

**Issue by unitezen** [ralexstokes/ethereum-consensus#389]
Is there a reason why the fields of PayloadAttributes are not public? Need some data from this type.

https://github.com/ralexstokes/ethereum-consensus/blob/72800f5e4cc28ad384f9cc7639d19da8dab50fb0/beacon-api-client/src/types.rs#L310-L322

**Comment by unitezen** [comment]
#390

**Comment by ralexstokes** [comment]
its yours!
